import asyncio
import os
import time
import logging
from playwright.async_api import async_playwright

log = logging.getLogger(__name__)

COOKIE_CACHE_FILE = "/tmp/douyin_auto_netscape_cookies.txt"

async def get_fresh_douyin_cookies(force: bool = False) -> str:
    now = time.time()
    if not force and os.path.exists(COOKIE_CACHE_FILE):
        mtime = os.path.getmtime(COOKIE_CACHE_FILE)
        if (now - mtime) < 600:
            return COOKIE_CACHE_FILE

    log.info("🌐 [AutoCookie] Gerando cookies autênticos do Douyin via Playwright (Zero Login)...")
    try:
        async with async_playwright() as p:
            browser = await p.chromium.launch(
                headless=True,
                args=[
                    "--no-sandbox",
                    "--disable-setuid-sandbox",
                    "--disable-blink-features=AutomationControlled"
                ]
            )
            context = await browser.new_context(
                viewport={"width": 1280, "height": 720},
                user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
            )
            page = await context.new_page()
            
            # Bloqueia recursos desnecessários para carregar instantaneamente
            async def block_resources(route):
                if route.request.resource_type in ["image", "media", "font", "stylesheet"]:
                    await route.abort()
                else:
                    await route.continue_()
            await page.route("**/*", block_resources)

            try:
                await page.goto("https://www.douyin.com/video/7212508820852002100", wait_until="commit", timeout=10000)
                await asyncio.sleep(3)
            except Exception as e_goto:
                log.warning(f"[AutoCookie] Aviso no page.goto: {e_goto}")

            cookies = await context.cookies()
            await browser.close()

            lines = ["# Netscape HTTP Cookie File", "# Auto-generated by Playwright Scrapper"]
            for c in cookies:
                domain = c.get("domain", ".douyin.com")
                if not domain.startswith("."):
                    domain = "." + domain
                path = c.get("path", "/")
                secure = "TRUE" if c.get("secure") else "FALSE"
                exp_val = c.get("expires")
                if exp_val is None or exp_val <= 0:
                    expires = "2147483647"
                else:
                    expires = str(int(exp_val))
                name = c.get("name")
                value = c.get("value")
                lines.append(f"{domain}	TRUE	{path}	{secure}	{expires}	{name}	{value}")

            with open(COOKIE_CACHE_FILE, "w", encoding="utf-8") as f:
                f.write("\n".join(lines) + "\n")

            log.info(f"✅ [AutoCookie] {len(cookies)} cookies atualizados salvos!")
            return COOKIE_CACHE_FILE
    except Exception as e:
        log.error(f"❌ [AutoCookie] Erro ao gerar cookies via Playwright: {e}")
        return ""

def get_douyin_cookie_file_sync(force: bool = False) -> str:
    try:
        try:
            loop = asyncio.get_running_loop()
        except RuntimeError:
            loop = None

        if loop and loop.is_running():
            import concurrent.futures
            with concurrent.futures.ThreadPoolExecutor(max_workers=1) as executor:
                future = executor.submit(lambda: asyncio.run(get_fresh_douyin_cookies(force=force)))
                return future.result()
        else:
            return asyncio.run(get_fresh_douyin_cookies(force=force))
    except Exception as e:
        log.error(f"[AutoCookie Sync] Erro: {e}")
        return ""


async def refresh_and_propagate_douyin_cookies(force: bool = False) -> str:
    """
    Roda Playwright para obter cookies frescos, formata-os como string de cabeçalho,
    salva na tabela user_settings do SQLite e propaga para a API Evil0ctal local.
    """
    cookie_file = await get_fresh_douyin_cookies(force=force)
    if not cookie_file or not os.path.exists(cookie_file):
        log.error("Failed to generate fresh Douyin cookies.")
        return ""

    cookies_list = []
    with open(cookie_file, "r", encoding="utf-8") as f:
        for line in f:
            if line.startswith("#") or not line.strip():
                continue
            parts = line.strip().split("\t")
            if len(parts) >= 7:
                name = parts[5]
                value = parts[6]
                cookies_list.append(f"{name}={value}")

    cookie_str = "; ".join(cookies_list)
    if not cookie_str:
        return ""

    # Atualiza SQLite database
    from src import database
    database.set_user_setting("DOUYIN_COOKIE", cookie_str)
    log.info("Saved fresh DOUYIN_COOKIE to database.")

    # Atualiza API Evil0ctal local
    from src.config import DOUYIN_API_BASE
    api_url = f"{DOUYIN_API_BASE}/api/hybrid/update_cookie"
    try:
        import httpx
        async with httpx.AsyncClient(timeout=10.0) as client:
            resp = await client.post(api_url, json={"service": "douyin", "cookie": cookie_str})
            if resp.status_code == 200:
                log.info("Successfully updated cookie in local Evil0ctal API.")
            else:
                log.warning(f"Failed to update cookie in local API. HTTP {resp.status_code}")
    except Exception as e:
        log.error(f"Error propagating cookie to local API: {e}")

    return cookie_str


def refresh_and_propagate_douyin_cookies_sync(force: bool = False) -> str:
    try:
        try:
            loop = asyncio.get_running_loop()
        except RuntimeError:
            loop = None

        if loop and loop.is_running():
            import concurrent.futures
            with concurrent.futures.ThreadPoolExecutor(max_workers=1) as executor:
                future = executor.submit(lambda: asyncio.run(refresh_and_propagate_douyin_cookies(force=force)))
                return future.result()
        else:
            return asyncio.run(refresh_and_propagate_douyin_cookies(force=force))
    except Exception as e:
        log.error(f"Error in refresh_and_propagate_douyin_cookies_sync: {e}")
        return ""


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    f = get_douyin_cookie_file_sync(force=True)
    print("Gerado:", f)

