import asyncio
import os
import time
import logging
from playwright.async_api import async_playwright

log = logging.getLogger(__name__)

COOKIE_CACHE_FILE = "/tmp/douyin_auto_netscape_cookies.txt"

async def get_fresh_douyin_cookies(force: bool = False) -> str:
    now = time.time()
    if not force and os.path.exists(COOKIE_CACHE_FILE):
        mtime = os.path.getmtime(COOKIE_CACHE_FILE)
        if (now - mtime) < 600:
            return COOKIE_CACHE_FILE

    log.info("🌐 [AutoCookie] Gerando cookies autênticos do Douyin via Playwright (Zero Login)...")
    try:
        async with async_playwright() as p:
            browser = await p.chromium.launch(
                headless=True,
                args=[
                    "--no-sandbox",
                    "--disable-setuid-sandbox",
                    "--disable-blink-features=AutomationControlled"
                ]
            )
            context = await browser.new_context(
                viewport={"width": 1280, "height": 720},
                user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
            )
            page = await context.new_page()
            try:
                await page.goto("https://www.douyin.com/", wait_until="domcontentloaded", timeout=20000)
                await asyncio.sleep(4)
            except Exception as e_goto:
                log.warning(f"[AutoCookie] Aviso no page.goto: {e_goto}")

            cookies = await context.cookies()
            await browser.close()

            lines = ["# Netscape HTTP Cookie File", "# Auto-generated by Playwright Scrapper"]
            for c in cookies:
                domain = c.get("domain", ".douyin.com")
                if not domain.startswith("."):
                    domain = "." + domain
                path = c.get("path", "/")
                secure = "TRUE" if c.get("secure") else "FALSE"
                exp_val = c.get("expires")
                if exp_val is None or exp_val <= 0:
                    expires = "2147483647"
                else:
                    expires = str(int(exp_val))
                name = c.get("name")
                value = c.get("value")
                lines.append(f"{domain}	TRUE	{path}	{secure}	{expires}	{name}	{value}")

            with open(COOKIE_CACHE_FILE, "w", encoding="utf-8") as f:
                f.write("\n".join(lines) + "\n")

            log.info(f"✅ [AutoCookie] {len(cookies)} cookies atualizados salvos!")
            return COOKIE_CACHE_FILE
    except Exception as e:
        log.error(f"❌ [AutoCookie] Erro ao gerar cookies via Playwright: {e}")
        return ""

def get_douyin_cookie_file_sync(force: bool = False) -> str:
    try:
        try:
            loop = asyncio.get_running_loop()
        except RuntimeError:
            loop = None

        if loop and loop.is_running():
            import concurrent.futures
            with concurrent.futures.ThreadPoolExecutor(max_workers=1) as executor:
                future = executor.submit(lambda: asyncio.run(get_fresh_douyin_cookies(force=force)))
                return future.result()
        else:
            return asyncio.run(get_fresh_douyin_cookies(force=force))
    except Exception as e:
        log.error(f"[AutoCookie Sync] Erro: {e}")
        return ""

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    f = get_douyin_cookie_file_sync(force=True)
    print("Gerado:", f)
